### ISSUE TITLE
No margin between consecutive tables

### ISSUE THREAD

**Issue by glimow** [rginestou/markdown-to-pdf-report#1]
![image](https://user-images.githubusercontent.com/26530171/60015631-3c1e9f00-9684-11e9-9767-b24088c3da85.png)
Steps to reproduce : Create two tables just one after another
Workaround: putting a `<br/>` between the two. But it's hacky and we shouldn't have to do that.

**Comment by rginestou** [comment]
Thanks for reporting that, fixed in [this commit](https://github.com/rginestou/MarkReport/commit/31e3ce61c89934b00a3ac4b8f86dd2f0887bce3f) by inserting CSS margins.
