### ISSUE TITLE
Bad margins when entering a new text page without header

### ISSUE THREAD

**Issue by glimow** [rginestou/markdown-to-pdf-report#2]
![image](https://user-images.githubusercontent.com/26530171/60015834-ba7b4100-9684-11e9-9fc0-17b61cf8aece.png)

Step to reproduce : create a text that is long enough so that it takes more than one page. At the beginning of the second page, the margins are too tiny.
Workaround: using a `<br/>`, but this is not robust to editing upstream

**Comment by rginestou** [comment]
Fixed in [this commit](https://github.com/rginestou/MarkReport/commit/9581edb20b0b491308b5f288a8251cb6e2e5f093) by adding a bottom margin to the header.
